# Generated by Django 4.2.1 on 2023-05-24 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColourVariant',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('colour', models.CharField(max_length=20)),
                ('unique_name', models.CharField(blank=True, editable=False, max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=500, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('category_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductStructure',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.CharField(max_length=50)),
                ('product_description', models.TextField()),
                ('common_specifications', tinymce.models.HTMLField()),
                ('unique_name', models.CharField(blank=True, editable=False, max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=500, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Catalogue.productcategory')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecsVariant',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.CharField(max_length=30)),
                ('variant_specifications', tinymce.models.HTMLField()),
                ('unique_name', models.CharField(blank=True, editable=False, max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True)),
                ('product_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogue.productstructure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('image_name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='Product_Images')),
                ('unique_image_name', models.CharField(blank=True, editable=False, max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=500, unique=True)),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogue.colourvariant')),
                ('product_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogue.productstructure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('product_name', models.CharField(blank=True, editable=False, max_length=180, null=True)),
                ('selling_price', models.IntegerField()),
                ('max_retail_price', models.IntegerField()),
                ('unique_product_name', models.CharField(blank=True, editable=False, max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=500, unique=True)),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogue.colourvariant')),
                ('product_images', models.ManyToManyField(blank=True, related_name='product_images', to='Catalogue.productimage')),
                ('product_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogue.productstructure')),
                ('product_thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_thumbnail', to='Catalogue.productimage')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogue.specsvariant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='colourvariant',
            name='product_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogue.productstructure'),
        ),
    ]
